# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  # TODO: imports = [ (pkgs.path + "/nixos/modules/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "aacraid" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/".device = "/dev/disk/by-label/nixos";
    "/var/lib/jenkins".device = "/dev/disk/by-label/jenkins";
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 64;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
