apiVersion: v1
kind: Service
metadata:
  name: {{ include "nixbld.fullname" . }}-load-balancer
  labels:
    {{- include "nixbld.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/vm: {{ include "nixbld.fullname" . }}
  type: LoadBalancer
